
apiVersion: v1
kind: ConfigMap
metadata:
  name: safekeeper-config
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: safekeeper
  labels:
    {{- include "neon.labels" . | nindent 4 }}
    app: safekeeper
spec:
  selector:
    matchLabels:
      app: safekeeper
  serviceName: safekeeper
  replicas: 3
  template:
    metadata:
      labels:
        app: safekeeper
    spec:
      initContainers:
      - name: storage-broker-wait
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup storage-broker.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for storage-broker; sleep 2; done"]
      containers:
      - name: safekeeper
        image: {{ .Values.safekeeper.image.repository }}:{{ .Values.safekeeper.image.tag }}
        ports:
        - containerPort: 5454
        - containerPort: 7676
        env:
        - name: SAFEKEEPER_ID
          value: "3"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: safekeeper-config
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: safekeeper-config
              key: AWS_SECRET_ACCESS_KEY
        command: ["safekeeper", "--listen-pg=0.0.0.0:5454", "--listen-http=0.0.0.0:7676", "--id=0", "--broker-endpoint=http://storage-broker.{{.Release.Namespace}}.svc.cluster.local:50051", "-D", "/data"]
---
apiVersion: v1
kind: Service
metadata:
  name: safekeeper
spec:
  selector:
    app: safekeeper
  ports:
  - name: wal
    port: 5454
    targetPort: 5454
  - name: http
    port: 7676
    targetPort: 7676
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: safekeeper-data-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/.neon/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safekeeper-data-claim
spec:
  storageClassName: "hostpath" #TODO: Add storage class later
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
