apiVersion: apps/v1
kind: Deployment
metadata:
    name: storage-broker
    labels:
        app: storage-broker
spec:
    replicas: 1
    selector:
        matchLabels:
            app: storage-broker
    template:
        metadata:
            labels:
                app: storage-broker
        spec:
            containers:
            - name: storage-broker
            image: neondatabase/storage-broker:latest
            ports:
            - containerPort: 8080
            env:
            - name: STORAGE_BROKER_PORT
              value: "8080"
            - name: STORAGE_BROKER_DB_URL
              value: "your-db-url"
            - name: STORAGE_BROKER_DB_USERNAME
              value: "your-db-username"
            - name: STORAGE_BROKER_DB_PASSWORD
              value: "your-db-password"
