name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Validate Helm Chart
      working-directory: charts/neon
      run: helm lint .

    - name: Create Kind Cluster
      uses: helm/kind-action@v1.8.0

    - name: Apply Helm Chart
      working-directory: charts/neon
      run: helm install neon .

    - name: Configure Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Package Helm Chart
      working-directory: charts/neon
      run: helm package .

    - name: Publish Helm Chart
      uses: helm/chart-releaser-action@v1.5.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
